export const CORE_SERVICE_CLIENT = Symbol('CORE_SERVICE_CLIENT');
export const OPERATIONS_SERVICE_CLIENT = Symbol('OPERATIONS_SERVICE_CLIENT');
export const MICROSERVICE_TIMEOUT = Symbol('MICROSERVICE_TIMEOUT');
